name: 'Update Flake Locks'
description: 'Updates all flake.lock files in the repository.'
outputs:
  lock-file-paths:
    description: "List of flake.lock files that were updated (newline separated)"
    value: ${{ steps.set-paths.outputs.paths }}
runs:
  using: "composite"
  steps:
    - name: Update flake.lock
      shell: bash
      run: |
        nix flake update --flake ./core
        nix flake update --flake ./extra/kernel/cachyos
        nix flake update --flake ./extra/kernel/cachyos-unstable
        nix flake update
        nix flake update --flake ./vps/tohu
        nix flake update --flake ./vps/hyperv

    - name: Set lock file paths
      id: set-paths
      shell: bash
      run: |
        # Define paths to lock files. This serves as the single source of truth.
        paths="flake.lock
        core/flake.lock
        extra/kernel/cachyos/flake.lock
        extra/kernel/cachyos-unstable/flake.lock
        vps/hyperv/flake.lock
        vps/tohu/flake.lock"
        
        # Emit output using GITHUB_OUTPUT environment file
        {
          echo "paths<<EOF"
          echo "$paths"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
