name: 'Replace Release String'
description: 'Replaces the pre-release flake input string with the main implementation string.'
runs:
  using: "composite"
  steps:
    - name: Modify String (Prepare for Main)
      shell: bash
      run: |
        # Replace github:ShaoG-R/nixos-config/pre-release with github:ShaoG-R/nixos-config
        sed -i 's|github:ShaoG-R/nixos-config/pre-release|github:ShaoG-R/nixos-config|g' flake.nix vps/tohu/flake.nix vps/hyperv/flake.nix
        
        # Verify replacement
        grep "github:ShaoG-R/nixos-config" flake.nix || true
        grep "github:ShaoG-R/nixos-config" vps/tohu/flake.nix || true
        grep "github:ShaoG-R/nixos-config" vps/hyperv/flake.nix || true
